### ISSUE TITLE
求支持专业学位

### ISSUE THREAD

**Issue by fys666** [Hthing/yzw#2]
求支持专业学位.
哥做的这个不支持专业学位，可以适配一下吗·？谢谢

**Comment by Hthing** [comment]
支持啊，例如电子信息：你直接用一级学科代码 0854 爬取就行了。 如果你指的是爬取研究方向就不行了。我是为了爬取全国所有专业写的，没必要分这么细。 你把全部的爬下来再自行筛选就行了
