### ISSUE TITLE
大佬，研招网界面有个小更新，用不成了，有没有计划更新一下

### ISSUE THREAD

**Issue by 646602196** [Hthing/yzw#3]
这个是具体的报错，我不太懂python爬虫方面的知识，所以不知道怎么改
![01E0A818](https://user-images.githubusercontent.com/42128890/133889277-77c27706-f82e-4c6f-99c9-323cd5c1fa30.gif)

2021-09-18 20:41:25 [schools] ERROR: Traceback (most recent call last):
  File "C:\Users\Mk\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_q
bz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\yzwspider\yzw\spid
ers\schools.py", line 83, in parse_major
    comments = majorInfo[5].css('.zsml-bz::text')
  File "C:\Users\Mk\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_q
bz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\parsel\selector.py
", line 70, in __getitem__
    o = super(SelectorList, self).__getitem__(pos)
IndexError: list index out of range

**Comment by myzhibei** [comment]
复议，大佬有空看到更新下不啦，哭了

**Comment by Hthing** [comment]
> 复议，大佬有空看到更新下不啦，哭了

改好了，只是研招网界面有点小改动。
顺便传了份今天的数据

**Comment by 646602196** [comment]
> > 复议，大佬有空看到更新下不啦，哭了
> 
> 改好了，只是研招网界面有点小改动。
> 顺便传了份今天的数据

感谢

**Comment by myzhibei** [comment]
> > 复议，大佬有空看到更新下不啦，哭了
> 
> 改好了，只是研招网界面有点小改动。
> 顺便传了份今天的数据

感谢大佬！！！

**Comment by myzhibei** [comment]
刚刚试了下，好像那个拟招生人数，有些是“专业：35（不含推免）”是正常的，但是有些专业显示的是“拟招人数：”就没了，好像没有人数，是不是有丢丢小问题

**Comment by Hthing** [comment]
> 刚刚试了下，好像那个拟招生人数，有些是“专业：35（不含推免）”是正常的，但是有些专业显示的是“拟招人数：”就没了，好像没有人数，是不是有丢丢小问题

我改完忘记核对数据了😥 现在应该可以了。。
